{
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,

  "forin": true,
  "immed": true,
  "latedef": "nofunc",
  "newcap": true,
  "noarg": true,
  "noempty": true,
  "nonew": true,
  "plusplus": false,
  "quotmark": "single",
  "undef": true,
  "unused": true,
  "strict": false,
  "trailing": false,
  "eqnull": true,
  "sub": true,
  "globals": {
    "angular": false,
    "_": false,
    "console": false,
    "Map":  false,
    "define": false,
    "describe": false,
    "it": false,
    "iit": false,
    "xit": false,
    "module": false,
    "inject": false,
    "expect": false,
    "beforeEach": false,
    "jasmine": false,
    "dump": false
  }
}
